---

- hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_user: ec2-user

  tasks:
    - name: Waiting for SSH connection
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300


- name: Configuring instance and installing apps
  hosts: all
  become: true

  vars:
    ansible_user: ec2-user

  tasks:

    - name: Install docker
      shell: "amazon-linux-extras install docker -y"

    - name: Iniciate and enable docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Install docker-compose
      shell: "curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose && chmod +x -R /usr/local/bin/docker-compose"

    - name: Install 2048
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user
        owner: root
        group: root
        mode: "0644"

    - name: Building and deploying 2048's image app
      shell: "docker-compose pull && docker-compose run -d"
