---

- hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_user: ec2-user

  tasks:
    - name: Waiting for SSH connection
      wait_for_connection:
        delay: 10
        sleep: 5
        timeout: 300


- name: Configuring instance and installing apps
  hosts: all
  become: true

  vars:
    ansible_user: ec2-user

  tasks:

    - name: Install docker
      shell: "amazon-linux-extras install docker -y"

    - name: Iniciate and enable docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Install docker-compose
      shell: "pip3 install docker-compose"

    - name: Downloading necessary's files
      shell: "wget https://github.com/MrSesioM/hello-2048/blob/main/docker-compose.yml"

    - name: Building and deploying 2048's image app
      shell: "docker-compose build && docker-compose run -d"
